---
title: "Events"
description: |
  News and Professional Journal - Updated once a month!
---


## June 2025

Visited varkala for the first time. An absolute delight to be at south/north cliff with an amazing company.

## May 2025

Got rid of the old phone - it was very slow and couldn't help but throw it away. 

## April 2025

We concluded 20th Let's Talk Spatial event - and it happened at IIIT Bangalore. With Professor Jasmeet Judge and Dr. Subhash as speakers.
It went wonderfully well - and good discussion as well



## March 2025

We had our 19th meetup at Varaha. It was good to be back organising meetups! And it was really good :) You can check out the video [here](https://www.youtube.com/live/kktb1KcIlOc?si=5tnZUN0YPZJqF9RA)

Conducted a hands-on workshop on Earth engine for climate at [BNMIT](https://youtu.be/vJa_6E5ArVw)

Was part of India Open LandCover Network meet that happened in collaboration with MapBiomas. Thoughtful discussion and lessons on how India can productionize this effort.


## Febuary 2025

Back to work. A lot of progress made thus far, but a long way to go. Let's Talk Spatial meetup has been in hibernation for some time and we are starting it next month.
Got to dive deep into workings of LLMs and how they could be used for geospatial technology. Very promising front to explore next couple of months.

## January 2025

I got married to love of my life. The whole month passed in a jiffy. We went to maldives at end of the month. Wonderful experience!

## December 2024

Wedding preparation is in beast MODE. Too less of a time remaining.

I got to deliver a talk on GeoPython at NMIT. As IEEE GRSS Young Professional Chair of Bangalore Section, I got to engage with the NMIT chapter and help them understand why this is the best time to be in Geospatial Industry

## November 2024

I got promoted at my job. Now I am a senior geospatial scientist ;)

Got done with wedding photoshoot, phew!

## October 2024

Started search for the best wedding outfits! Now I know a lot about clothing - and have a better sense of judgement!

## September 2024

Attended SAC event on the occasion of National Space Day! The excitement was palpable, as it was the first time private industry was invited inside SAC.

Friends (and colleagues) went on a vacation to Puducherry! Maybe the last one before my marriage.

## August 2024

Conducted a workshop on QGIS for Let's Talk Spatial. You can watch it [here](https://www.youtube.com/live/07rbTdK8huw)

## July 2024

Met with an accident on two-wheeler while driving back home! Broke my leg, WFH for atleast a week!

Conducted (online) workshop on QGIS for ACIWRM. First time an online workshop - was super helpful for me to revise all the important concepts. The team loved it!
Email me at amanbagrecha.blr@gmail.com if you'd like to conduct such workshops!

Got Selected for [IADF School](https://iadf-school.org/) happening in Italy! Fingers crossed - hopefully my visa gets accepted!

## June 2024

Birthday month - and had to visit a lot of event planners for my wedding! It is tiring TBH :(

## May 2024

Conducted workshop at NIE on Google Earth Engine for the 2nd time. The students loved it, again!

Let's Talk Spatial had its 16th meetup at Microsoft Reactor Space, Bangalore! on geospatial AI. The recording can be watched [here](https://www.youtube.com/live/TKbMYmXXbo8)




## April 2024
I found my life partner in my best friend and travel buddy - I am engaged!

Hosted a hackathon in collaboration with SkyServe. A good number of participants from across the country took the challenge to create AI models for the Edge! Details [here](https://www.linkedin.com/feed/update/urn:li:activity:7189333318394429441). The webinar can be found [here](https://www.youtube.com/live/9B4UNJqKos4?si=moId51V3LvcfBLeV)


## March 2024
Took a small vacation with Family to beat the Bangalore heat, off to Goa! 

Hosted a meetup in collobration with [Proto](https://www.proto-geo.xyz/). The event revolved around maps and content. Super fun audience and speakers. The live stream can be watched [here](https://youtube.com/live/YnJ3FHUXhv4)

## Febuary 2024
I conducted a [workshop](https://www.linkedin.com/posts/amanbagrecha_wrapping-up-last-two-eventful-days-first-activity-7164916975444447232-f-UN) on [Google Earth Engine](https://earthengine.google.com/) at The National Institute of Engineering, Mysore. Also attended AGM of (IEEE GRSS Bangalore Section](https://site.ieee.org/bangalore-grss/) at Manipal Institute of Management, MAHE, Bangalore.

## January 2024
It was a hectic month both professionally and personally! So many things piled up!

## December 2023

Attended (and organised) InGARSS 2023, which happened in IIIT Bangalore. I was the YP Chair - helping organize 2 events.

I took year end break and went on vacation. This year was by far the most I've travelled. Wish to do the same this year (maybe even more)!

## November 2023
Attended FOSS4G Asia in Seoul - co-conducted workshop on [GeoPython](https://github.com/Rotten-Grapes-Pvt-Ltd/geopython-workshop) and also gave a talk on [Sentinel-1 Image Analysis Flood detection using cloud native tooling](https://github.com/amanbagrecha/Foss4gAsia2023). South Korea was a experience to be lived. It was chilly outside, but I had good company throughout. Found Indian food luckily :)

We also had our [13th meetup](https://twitter.com/letstalkspatial/status/1725733833688129980) at Indian Institute of Human Settlements in collaboration with OpenStreetMap Bengaluru - to talk about OSM and iD editor. The presenters also showcased map making using QGIS.

Our paper [Climate responsive design for road surface drainage systems: a case study for city of Bengaluru](https://www.tandfonline.com/doi/abs/10.1080/1573062X.2023.2287049) got accepted in Urban water Journal!



## October 2023

I conducted [workshop](https://www.youtube.com/watch?v=lUMjcau7JAs) on Planetary Computer and STAC API which was also the 12th meetup conducted by Let's Talk Spatial. 

I attended [Geosmart Conference](https://geosmartindia.net/2023/index.php) in Hyderabad. A lot of geospatial companies were present. Made many new connections and got to know about latest trends and how the indian geospatial community is up to. 


## September 2023
I joined [GalaxEye](https://www.galaxeye.space/)!

We organised mapping party in Chamrajpet, Bengaluru! Read my OSM Diary [here](https://www.openstreetmap.org/user/aman_bagrecha/diary/402347).

## June - July 2023

I attended FOSS4G for the very first time and gave two talks. I had the most memorable experience in Prizren. Read in-depth blog [here](../posts/first-foss4g).
